apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chainerjobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: chainerjobs
    singular: chainerjob
    kind: ChainerJob
    shortNames:
    - chj
    - chjs
    - chjob
    - chjobs
    categories:
    - all
