// Copyright 2018 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeflow/chainer-operator/pkg/apis/chainer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChainerJobs implements ChainerJobInterface
type FakeChainerJobs struct {
	Fake *FakeKubeflowV1alpha1
	ns   string
}

var chainerjobsResource = schema.GroupVersionResource{Group: "kubeflow.org", Version: "v1alpha1", Resource: "chainerjobs"}

var chainerjobsKind = schema.GroupVersionKind{Group: "kubeflow.org", Version: "v1alpha1", Kind: "ChainerJob"}

// Get takes name of the chainerJob, and returns the corresponding chainerJob object, and an error if there is any.
func (c *FakeChainerJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.ChainerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chainerjobsResource, c.ns, name), &v1alpha1.ChainerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChainerJob), err
}

// List takes label and field selectors, and returns the list of ChainerJobs that match those selectors.
func (c *FakeChainerJobs) List(opts v1.ListOptions) (result *v1alpha1.ChainerJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chainerjobsResource, chainerjobsKind, c.ns, opts), &v1alpha1.ChainerJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChainerJobList{ListMeta: obj.(*v1alpha1.ChainerJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChainerJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chainerJobs.
func (c *FakeChainerJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chainerjobsResource, c.ns, opts))

}

// Create takes the representation of a chainerJob and creates it.  Returns the server's representation of the chainerJob, and an error, if there is any.
func (c *FakeChainerJobs) Create(chainerJob *v1alpha1.ChainerJob) (result *v1alpha1.ChainerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chainerjobsResource, c.ns, chainerJob), &v1alpha1.ChainerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChainerJob), err
}

// Update takes the representation of a chainerJob and updates it. Returns the server's representation of the chainerJob, and an error, if there is any.
func (c *FakeChainerJobs) Update(chainerJob *v1alpha1.ChainerJob) (result *v1alpha1.ChainerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chainerjobsResource, c.ns, chainerJob), &v1alpha1.ChainerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChainerJob), err
}

// Delete takes name of the chainerJob and deletes it. Returns an error if one occurs.
func (c *FakeChainerJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chainerjobsResource, c.ns, name), &v1alpha1.ChainerJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChainerJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chainerjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChainerJobList{})
	return err
}

// Patch applies the patch and returns the patched chainerJob.
func (c *FakeChainerJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChainerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chainerjobsResource, c.ns, name, data, subresources...), &v1alpha1.ChainerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChainerJob), err
}
